project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!files/"
  resources:
    - "*.json"
    - "files"
    - "_extensions"

execute:
  freeze: auto


website:
  repo-url: https://github.com/inqs909/d300_f26
  title: "Data 300"
  site-url: www.inqs.info/d300_f26
  navbar:
    right:
      - syllabus.qmd
      - lectures.qmd
      - project_report.qmd




format:
  html:
    theme:
      light: themes.scss
    toc: true


